# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvZCl3YalKkfl-dr2URVvvmb7esgN6RA
"""

import math
import matplotlib.pyplot as plt
from matplotlib.widgets import TextBox
import pandas as pd



TEAL = '#0D9488'
AMBER = '#F59E0B'
PURPLE = '#8B5CF6'
BLUE = '#3B82F6'
RED = '#EF4444'
GRAY = '#94A3B8'


plt.rcParams.update({
    'figure.figsize': (10, 5),
    'axes.spines.top': False,
    'axes.spines.right': False,
    'axes.labelsize': 12,
    'axes.titlesize': 14,
    'font.family': 'DejaVu Sans',
})

# Código com as fórmulas implementadas
# formula do tempo de voo
def calcular_tempo_voo(
    v0, theta_rad, y0, g
):  # o theta é recebido em GRAUS, ele é convertido para radianos
    v0y = v0 * math.sin(theta_rad)
    termo_raiz = v0y**2 + 2 * g * y0
    t_voo = (v0y + math.sqrt(termo_raiz)) / g
    return t_voo


# formula da altura máxima
def calcular_altura_max(v0, theta_rad, y0, g):
    v0y = v0 + math.sin(theta_rad)
    y_max = y0 + (v0y**2) / (2 * g)
    return y_max


# Alcançe
def calcular_alcance(v0, theta_rad, x0, t_voo):
    R = x0 + v0 * math.cos(theta_rad) * t_voo
    return R


# Função para os slides e GUI
def calcular_results(v0, theta_graus, x0, y0, g):
    theta_rad = math.radians(theta_graus)

    t_voo = calcular_tempo_voo(v0, theta_rad, y0, g)
    y_max = calcular_altura_max(v0, theta_rad, y0, g)
    R = calcular_alcance(v0, theta_rad, x0, t_voo)

    return {
        "tempo_voo": t_voo,
        "altura_maxima": y_max,
        "alcance": R,
    }


# Função para gerar os pontos (x, y)
def calcular_trajet(v0, theta_graus, x0, y0, g, num_pontos=200):
    theta_rad = math.radians(theta_graus)
    t_voo = calcular_tempo_voo(v0, theta_rad, y0, g)

    # amostra num_pontos instantes igualmente espaçados entre 0 e o tempo de voo
    tempos = [t_voo * i / (num_pontos - 1) for i in range(num_pontos)]

    xs = [x0 + y0 * math.cos(theta_rad) * t for t in tempos]
    ys = [y0 + v0 * math.sin(theta_rad) * t - 0.5 * g * t**2 for t in tempos]

    return xs, ys, tempos

"""O usuario consegue alterar parâmetros  pela interface"""

print("Velocidade Inicial v0 (m/s):")

vel_ini = float(input(" "))
print()

print("Ângulo θ (graus):")

angulo = float(input(" "))
print()

print("Altura Inicial y0 (m):")

alt_ini = float(input(" "))
print()

print("Gravidade g (m/s²):")

gravidade = float(input(" "))
print()

#chamando função
x0=0.0
resultados=calcular_results(vel_ini, angulo, x0, alt_ini, gravidade)

print("Resultados do lançamento")
print(f"Alcance Total (R): {resultados['alcance']:.2f} metros")
print(f"Altura Máxima (ymax): {resultados['altura_maxima']:.2f} metros")
print(f"Tempo de Voo (tvoo): {resultados['tempo_voo']:.2f} segundos")

xs, ys, tempos = calcular_trajet(vel_ini, angulo, x0, alt_ini, gravidade)

#Tamanho figura
fig, ax = plt.subplots()
#Tamanho caixa do grafico
plt.subplots_adjust(bottom=0.40)

# Posições de cada caixa
pos_v0    = plt.axes([0.25, 0.20, 0.15, 0.04])
pos_theta = plt.axes([0.25, 0.10, 0.15, 0.04])
pos_y0    = plt.axes([0.65, 0.20, 0.15, 0.04])
pos_g     = plt.axes([0.65, 0.10, 0.15, 0.04])

#Cada caixa com sua variavel
caixa_v0    = TextBox(pos_v0, 'Velocidade v0 (m/s): ', initial=str(vel_ini))
caixa_theta = TextBox(pos_theta, 'Ângulo θ (graus): ', initial=str(angulo))
caixa_y0    = TextBox(pos_y0, 'Altura Inicial y0 (m): ', initial=str(alt_ini))
caixa_g     = TextBox(pos_g, 'Gravidade g (m/s²): ', initial=str(gravidade))


def atualizar(texto_digitado):
  #Modificando grafico
    try:

        global vel_ini, angulo, alt_ini, gravidade
        vel_ini   = float(caixa_v0.text)
        angulo    = float(caixa_theta.text)
        alt_ini   = float(caixa_y0.text)
        gravidade = float(caixa_g.text)

        #Pontos no grafico
        xs, ys, _ = calcular_trajet(vel_ini, angulo, x0, alt_ini, gravidade)

        # Limpa e desenha a nova curva usando sua cor roxa
        ax.clear()
        ax.plot(xs, ys, color=PURPLE, linewidth=2.5)

        # Faz o gráfico se ajustar perfeitamente aos limites numéricos reais
        ax.relim()
        ax.autoscale_view()

        # Reaplica seu layout estético limpo
        ax.set_title("Simulador de Lançamento de Projéteis", color=RED, fontweight='bold')
        ax.set_xlabel("Distância Horizontal (m)", color=GRAY)
        ax.set_ylabel("Altura (m)", color=GRAY)
        ax.grid(True, linestyle=":", alpha=0.5)
        ax.set_aspect('equal', adjustable='box')

        plt.draw()
        #para se usuario não escrever nada
    except ValueError:
        pass

# Vincula as caixas de texto ao atualizador inteligente
caixa_v0.on_submit(atualizar)
caixa_theta.on_submit(atualizar)
caixa_y0.on_submit(atualizar)
caixa_g.on_submit(atualizar)

# Inicializa o gráfico desenhado na primeira abertura de tela
atualizar(None)

plt.show()

